// Thai language strings for the front-store POS screen.
export const th = {
  frontRegister: 'หน้าร้าน (แคชเชียร์)',
  retail: 'ขายปลีก',
  wholesale: 'ขายส่ง',
  backStore: 'หลังร้าน',
  signOut: 'ออกจากระบบ',
  searchPlaceholder: 'สแกนบาร์โค้ด หรือค้นหาสินค้า / รหัส SKU…',
  camera: 'กล้อง',
  favorites: 'สินค้าขายดี',
  allProducts: 'สินค้าทั้งหมด',
  searchResults: 'ผลการค้นหา',
  noProducts: 'ไม่พบสินค้า',
  emptyCartTitle: 'สแกนหรือเลือกสินค้าเพื่อเริ่มขาย',
  emptyCartHint: 'เครื่องสแกนบาร์โค้ดทำงานอัตโนมัติ — แค่สแกนได้เลย',
  order: 'รายการขาย',
  items: 'ชิ้น',
  item: 'สินค้า',
  qty: 'จำนวน',
  price: 'ราคา',
  total: 'รวม',
  subtotal: 'ยอดรวมย่อย',
  taxIncl: 'ภาษี (รวมแล้ว)',
  taxExcl: 'ภาษี (ไม่รวม)',
  totalDue: 'ยอดที่ต้องชำระ',
  charge: 'รับชำระเงิน',
  clearOrder: 'ล้างรายการ',
  stock: 'คงเหลือ',
  outOfStock: 'สินค้าหมด',
  wholesaleBadge: 'ราคาส่ง',
  needMoreForWholesale: (n: number) => `ซื้อ ≥${n} เพื่อราคาส่ง`,
  added: (n: string) => `เพิ่ม ${n} แล้ว`,
  notFound: (c: string) => `ไม่พบสินค้ารหัส "${c}"`,
  // Payment
  takePayment: 'รับชำระเงิน',
  cash: 'เงินสด',
  transfer: 'โอนเงิน (พร้อมเพย์)',
  cashReceived: 'รับเงินมา',
  exact: 'พอดี',
  reset: 'ล้าง',
  change: 'เงินทอน',
  cancel: 'ยกเลิก',
  confirmCash: 'ยืนยันเงินสด',
  markPaid: 'ยืนยันการชำระ',
  processing: 'กำลังดำเนินการ…',
  generatingQR: 'กำลังสร้าง QR…',
  thaiQR: 'ชำระเงินด้วย QR',
  amount: 'จำนวนเงิน',
  scanToPay: 'สแกนด้วยแอปธนาคารใดก็ได้ เพื่อชำระให้',
  noPromptPay: 'ยังไม่ได้ตั้งค่าพร้อมเพย์ — ไปที่ หลังร้าน → ตั้งค่า',
  // Receipt
  paymentComplete: 'ชำระเงินสำเร็จ',
  newOrder: 'รายการใหม่',
  // Shift
  openShift: 'เปิดกะ',
  closeShift: 'ปิดกะ',
  openingFloat: 'เงินทอนตั้งต้น',
  openShiftTitle: 'เปิดกะการขาย',
  openShiftHint: 'ใส่จำนวนเงินสดตั้งต้นในลิ้นชักเพื่อเริ่มขาย',
  startSelling: 'เริ่มขาย',
  shift: 'กะ',
  closeShiftTitle: 'ปิดกะและสรุปยอด',
  countedCash: 'นับเงินสดจริง',
  expectedCash: 'เงินสดที่ควรมี',
  difference: 'ส่วนต่าง',
  cashSales: 'ขายเงินสด',
  transferSales: 'ขายเงินโอน',
  orders: 'จำนวนบิล',
  confirmClose: 'ยืนยันปิดกะ',
  shiftClosed: 'ปิดกะเรียบร้อย',
  splitPayment: 'แยกชำระ (หลายช่องทาง)',
  addTender: 'เพิ่มช่องทางชำระ',
  // Petty cash (drawer pay-in / pay-out)
  cashInOut: 'เงินเข้า-ออก',
  cashDrawerTitle: 'เงินเข้า-ออกลิ้นชัก',
  payIn: 'เงินเข้า',
  payOut: 'เงินออก',
  cashReason: 'เหตุผล / หมายเหตุ',
  cashReasonHint: 'เช่น เติมเงินทอน, จ่ายค่าน้ำ-ไฟ, ถอนเงินฝากธนาคาร',
  recordCash: 'บันทึกรายการ',
  cashRecorded: 'บันทึกเงินเข้า-ออกแล้ว',
  noCashMoves: 'ยังไม่มีรายการเงินเข้า-ออก',
  xReport: 'รายงานยอดขาย (X)',
  zReport: 'พิมพ์รายงานปิดกะ (Z)',
  printReport: 'พิมพ์รายงาน',
  // Member
  member: 'สมาชิก',
  selectMember: 'เลือกสมาชิก',
  searchMember: 'ค้นหาด้วยชื่อ หรือเบอร์โทร…',
  noMember: 'ลูกค้าทั่วไป',
  addMember: 'เพิ่มสมาชิกใหม่',
  memberName: 'ชื่อสมาชิก',
  phone: 'เบอร์โทร',
  save: 'บันทึก',
  remove: 'นำออก',
  memberPrice: 'ราคาสมาชิก',
  max: 'สูงสุด',
  // Loyalty points
  pointsUnit: 'แต้ม',
  pointsBalance: 'แต้มสะสม',
  usePoints: 'ใช้แต้มสะสม',
  pointsRedeemed: 'ส่วนลดจากแต้ม',
  pointsEarned: 'ได้รับแต้ม',
  // Customer display
  customerDisplay: 'จอลูกค้า',
  welcome: 'ยินดีต้อนรับ',
  pleaseScan: 'สแกน QR เพื่อชำระเงิน',
  waitingPayment: 'รอการชำระเงิน',
  thankYou: 'ขอบคุณที่ใช้บริการ',

  // ---- BizPro-style POS layout ----
  posTitle: 'หน้าขายสินค้า (POS)',
  online: 'Online',
  searchFull: 'ค้นหาสินค้า / สแกนบาร์โค้ด / ชื่อ / รหัสสินค้า',
  // action toolbar
  aCustomer: 'ลูกค้า',
  aPromotion: 'โปรโมชั่น',
  aDiscount: 'ราคา/ส่วนลด',
  aHold: 'พักบิล',
  aLastBill: 'บิลล่าสุด',
  aMore: 'เพิ่มเติม',
  // KPIs
  kSalesToday: 'ยอดขายวันนี้',
  kSalesMonth: 'ยอดขายเดือนนี้',
  kProfitToday: 'กำไรขั้นต้นวันนี้',
  kCustomersToday: 'ลูกค้าวันนี้',
  kBills: 'บิล',
  kFromLastMonth: 'จากเดือนที่แล้ว',
  kAvgPurchase: 'ยอดซื้อเฉลี่ย',
  // categories & filters
  cAll: 'ทั้งหมด',
  manageCategories: 'จัดการหมวดหมู่',
  fBestSeller: 'ขายดี',
  fAll: 'ทั้งหมด',
  fBrand: 'ยี่ห้อ',
  fStockStatus: 'สถานะสต็อก',
  // badges
  bBestSeller: 'ขายดี',
  bPromo: 'โปร',
  bLow: 'ใกล้หมด',
  bOut: 'หมดสต็อก',
  // grid / pagination
  show: 'แสดง',
  perPage: '/ หน้า',
  // cart
  currentBill: 'บิลปัจจุบัน',
  customerInfo: 'ข้อมูลลูกค้า',
  changeCustomer: 'เปลี่ยนลูกค้า',
  generalCustomer: 'ลูกค้าทั่วไป',
  regularCustomer: 'ลูกค้าประจำ',
  cProduct: 'สินค้า',
  cQty: 'จำนวน',
  cPrice: 'ราคา',
  cSum: 'รวม',
  discountCoupon: 'ส่วนลด / คูปอง',
  add: 'เพิ่ม',
  subtotalItems: 'รวมราคาสินค้า',
  billDiscount: 'ส่วนลดบิล',
  vatLabel: 'ภาษีมูลค่าเพิ่ม',
  netTotal: 'ยอดสุทธิ',
  received: 'ได้รับเงิน',
  // payment methods
  pmCash: 'เงินสด',
  pmTransfer: 'โอนเงิน',
  pmCard: 'บัตรเครดิต',
  pmQR: 'QR Code',
  pmCredit: 'เงินเชื่อ',
  pay: 'ชำระเงิน',
  emptyBill: 'ยังไม่มีสินค้าในบิล',
  scanToStart: 'สแกนหรือเลือกสินค้าเพื่อเริ่มขาย',
  comingSoon: 'ฟีเจอร์นี้กำลังจะมาเร็ว ๆ นี้',
  held: 'พักบิลแล้ว',
  noHeld: 'ไม่มีบิลที่พักไว้',
  confirmPayment: 'ยืนยันการชำระเงิน',
  branch: 'สาขา',
  switchBranch: 'เปลี่ยนสาขา',
  offlineSaleQueued: 'บันทึกการขายแบบออฟไลน์ — จะซิงค์อัตโนมัติเมื่อกลับมาออนไลน์',
  pendingSync: 'รอซิงค์',
  syncNow: 'ซิงค์เดี๋ยวนี้',
  syncing: 'กำลังซิงค์…',
  offline: 'ออฟไลน์',
  foreignCash: 'รับเงินสดสกุลต่างประเทศ',
  foreignTender: 'เงินต่างสกุล',
};
