// UI strings + i18n. The active dictionary is chosen once at module load from the saved
// language; `th` is exported as that dictionary so all existing `th.x` call sites work
// unchanged (toggling language calls setLang(), which persists + reloads). Thai is the
// default; English is an opt-in. NOTE: some components still have inline Thai literals not
// routed through here — those stay Thai until migrated (the toggle covers this central table).

const thDict = {
  frontRegister: 'หน้าร้าน (แคชเชียร์)',
  retail: 'ขายปลีก',
  wholesale: 'ขายส่ง',
  backStore: 'หลังร้าน',
  signOut: 'ออกจากระบบ',
  searchPlaceholder: 'สแกนบาร์โค้ด หรือค้นหาสินค้า / รหัส SKU…',
  camera: 'กล้อง',
  favorites: 'สินค้าขายดี',
  allProducts: 'สินค้าทั้งหมด',
  searchResults: 'ผลการค้นหา',
  noProducts: 'ไม่พบสินค้า',
  emptyCartTitle: 'สแกนหรือเลือกสินค้าเพื่อเริ่มขาย',
  emptyCartHint: 'เครื่องสแกนบาร์โค้ดทำงานอัตโนมัติ — แค่สแกนได้เลย',
  order: 'รายการขาย',
  items: 'ชิ้น',
  item: 'สินค้า',
  qty: 'จำนวน',
  price: 'ราคา',
  total: 'รวม',
  subtotal: 'ยอดรวมย่อย',
  taxIncl: 'ภาษี (รวมแล้ว)',
  taxExcl: 'ภาษี (ไม่รวม)',
  totalDue: 'ยอดที่ต้องชำระ',
  charge: 'รับชำระเงิน',
  clearOrder: 'ล้างรายการ',
  stock: 'คงเหลือ',
  outOfStock: 'สินค้าหมด',
  wholesaleBadge: 'ราคาส่ง',
  needMoreForWholesale: (n: number) => `ซื้อ ≥${n} เพื่อราคาส่ง`,
  added: (n: string) => `เพิ่ม ${n} แล้ว`,
  notFound: (c: string) => `ไม่พบสินค้ารหัส "${c}"`,
  takePayment: 'รับชำระเงิน',
  cash: 'เงินสด',
  transfer: 'โอนเงิน (พร้อมเพย์)',
  cashReceived: 'รับเงินมา',
  exact: 'พอดี',
  reset: 'ล้าง',
  change: 'เงินทอน',
  cancel: 'ยกเลิก',
  confirmCash: 'ยืนยันเงินสด',
  markPaid: 'ยืนยันการชำระ',
  processing: 'กำลังดำเนินการ…',
  generatingQR: 'กำลังสร้าง QR…',
  thaiQR: 'ชำระเงินด้วย QR',
  amount: 'จำนวนเงิน',
  scanToPay: 'สแกนด้วยแอปธนาคารใดก็ได้ เพื่อชำระให้',
  noPromptPay: 'ยังไม่ได้ตั้งค่าพร้อมเพย์ — ไปที่ หลังร้าน → ตั้งค่า',
  paymentComplete: 'ชำระเงินสำเร็จ',
  newOrder: 'รายการใหม่',
  openShift: 'เปิดกะ',
  closeShift: 'ปิดกะ',
  openingFloat: 'เงินทอนตั้งต้น',
  openShiftTitle: 'เปิดกะการขาย',
  openShiftHint: 'ใส่จำนวนเงินสดตั้งต้นในลิ้นชักเพื่อเริ่มขาย',
  startSelling: 'เริ่มขาย',
  shift: 'กะ',
  closeShiftTitle: 'ปิดกะและสรุปยอด',
  countedCash: 'นับเงินสดจริง',
  expectedCash: 'เงินสดที่ควรมี',
  difference: 'ส่วนต่าง',
  cashSales: 'ขายเงินสด',
  transferSales: 'ขายเงินโอน',
  orders: 'จำนวนบิล',
  confirmClose: 'ยืนยันปิดกะ',
  shiftClosed: 'ปิดกะเรียบร้อย',
  splitPayment: 'แยกชำระ (หลายช่องทาง)',
  addTender: 'เพิ่มช่องทางชำระ',
  cashInOut: 'เงินเข้า-ออก',
  cashDrawerTitle: 'เงินเข้า-ออกลิ้นชัก',
  payIn: 'เงินเข้า',
  payOut: 'เงินออก',
  cashReason: 'เหตุผล / หมายเหตุ',
  cashReasonHint: 'เช่น เติมเงินทอน, จ่ายค่าน้ำ-ไฟ, ถอนเงินฝากธนาคาร',
  recordCash: 'บันทึกรายการ',
  cashRecorded: 'บันทึกเงินเข้า-ออกแล้ว',
  noCashMoves: 'ยังไม่มีรายการเงินเข้า-ออก',
  xReport: 'รายงานยอดขาย (X)',
  zReport: 'พิมพ์รายงานปิดกะ (Z)',
  printReport: 'พิมพ์รายงาน',
  member: 'สมาชิก',
  selectMember: 'เลือกสมาชิก',
  searchMember: 'ค้นหาด้วยชื่อ หรือเบอร์โทร…',
  noMember: 'ลูกค้าทั่วไป',
  addMember: 'เพิ่มสมาชิกใหม่',
  memberName: 'ชื่อสมาชิก',
  phone: 'เบอร์โทร',
  save: 'บันทึก',
  remove: 'นำออก',
  memberPrice: 'ราคาสมาชิก',
  max: 'สูงสุด',
  pointsUnit: 'แต้ม',
  pointsBalance: 'แต้มสะสม',
  usePoints: 'ใช้แต้มสะสม',
  pointsRedeemed: 'ส่วนลดจากแต้ม',
  pointsEarned: 'ได้รับแต้ม',
  customerDisplay: 'จอลูกค้า',
  welcome: 'ยินดีต้อนรับ',
  pleaseScan: 'สแกน QR เพื่อชำระเงิน',
  waitingPayment: 'รอการชำระเงิน',
  thankYou: 'ขอบคุณที่ใช้บริการ',
  posTitle: 'หน้าขายสินค้า (POS)',
  online: 'Online',
  searchFull: 'ค้นหาสินค้า / สแกนบาร์โค้ด / ชื่อ / รหัสสินค้า',
  aCustomer: 'ลูกค้า',
  aPromotion: 'โปรโมชั่น',
  aDiscount: 'ราคา/ส่วนลด',
  aHold: 'พักบิล',
  aLastBill: 'บิลล่าสุด',
  aMore: 'เพิ่มเติม',
  kSalesToday: 'ยอดขายวันนี้',
  kSalesMonth: 'ยอดขายเดือนนี้',
  kProfitToday: 'กำไรขั้นต้นวันนี้',
  kCustomersToday: 'ลูกค้าวันนี้',
  kBills: 'บิล',
  kFromLastMonth: 'จากเดือนที่แล้ว',
  kAvgPurchase: 'ยอดซื้อเฉลี่ย',
  cAll: 'ทั้งหมด',
  manageCategories: 'จัดการหมวดหมู่',
  fBestSeller: 'ขายดี',
  fAll: 'ทั้งหมด',
  fBrand: 'ยี่ห้อ',
  fStockStatus: 'สถานะสต็อก',
  bBestSeller: 'ขายดี',
  bPromo: 'โปร',
  bLow: 'ใกล้หมด',
  bOut: 'หมดสต็อก',
  show: 'แสดง',
  perPage: '/ หน้า',
  currentBill: 'บิลปัจจุบัน',
  customerInfo: 'ข้อมูลลูกค้า',
  changeCustomer: 'เปลี่ยนลูกค้า',
  generalCustomer: 'ลูกค้าทั่วไป',
  regularCustomer: 'ลูกค้าประจำ',
  cProduct: 'สินค้า',
  cQty: 'จำนวน',
  cPrice: 'ราคา',
  cSum: 'รวม',
  discountCoupon: 'ส่วนลด / คูปอง',
  add: 'เพิ่ม',
  subtotalItems: 'รวมราคาสินค้า',
  billDiscount: 'ส่วนลดบิล',
  vatLabel: 'ภาษีมูลค่าเพิ่ม',
  netTotal: 'ยอดสุทธิ',
  received: 'ได้รับเงิน',
  pmCash: 'เงินสด',
  pmTransfer: 'โอนเงิน',
  pmCard: 'บัตรเครดิต',
  pmQR: 'QR Code',
  pmCredit: 'เงินเชื่อ',
  pay: 'ชำระเงิน',
  emptyBill: 'ยังไม่มีสินค้าในบิล',
  scanToStart: 'สแกนหรือเลือกสินค้าเพื่อเริ่มขาย',
  comingSoon: 'ฟีเจอร์นี้กำลังจะมาเร็ว ๆ นี้',
  held: 'พักบิลแล้ว',
  noHeld: 'ไม่มีบิลที่พักไว้',
  confirmPayment: 'ยืนยันการชำระเงิน',
  branch: 'สาขา',
  switchBranch: 'เปลี่ยนสาขา',
  offlineSaleQueued: 'บันทึกการขายแบบออฟไลน์ — จะซิงค์อัตโนมัติเมื่อกลับมาออนไลน์',
  pendingSync: 'รอซิงค์',
  syncNow: 'ซิงค์เดี๋ยวนี้',
  syncing: 'กำลังซิงค์…',
  offline: 'ออฟไลน์',
  foreignCash: 'รับเงินสดสกุลต่างประเทศ',
  foreignTender: 'เงินต่างสกุล',
  pendingSyncTitle: 'รายการขายออฟไลน์ที่รอซิงค์',
  pendingSyncEmpty: 'ไม่มีรายการรอซิงค์',
  syncFailed: 'ซิงค์ไม่สำเร็จ',
  discard: 'ลบ',
  discardConfirm: 'ลบรายการขายออฟไลน์นี้? รายการนี้จะไม่ถูกบันทึกเข้าระบบ',
  serverConnect: 'ตั้งค่าการเชื่อมต่อเซิร์ฟเวอร์',
  serverUrl: 'ที่อยู่เซิร์ฟเวอร์ POS (URL)',
  serverHint: 'เช่น http://192.168.1.50:4000 — เว้นว่างเพื่อใช้เซิร์ฟเวอร์เดียวกับที่เปิดแอปนี้',
  serverSaved: 'บันทึกการเชื่อมต่อแล้ว กำลังโหลดใหม่…',
  serverReachable: 'เชื่อมต่อเซิร์ฟเวอร์สำเร็จ ✓',
  serverUnreachable: 'เชื่อมต่อเซิร์ฟเวอร์ไม่สำเร็จ',
  testConnection: 'ทดสอบการเชื่อมต่อ',
  back: 'ย้อนกลับ',
  desktopSetupTitle: 'ตั้งค่าเริ่มต้น',
  desktopSetupSub: 'เลือกบทบาทของเครื่องนี้เพื่อเริ่มใช้งาน POS',
  roleServer: 'เครื่องแม่ข่าย (Server)',
  roleServerHint: 'เครื่องนี้เป็นเครื่องหลักที่เก็บข้อมูล/ให้บริการ POS แก่เครื่องอื่นในร้าน',
  roleClient: 'เครื่องลูกข่าย (Client)',
  roleClientHint: 'เครื่องขายที่เชื่อมต่อไปยังเครื่องแม่ข่ายของร้าน',
  roleServerNote: 'เครื่องนี้จะเปิดเซิร์ฟเวอร์ POS เอง (พอร์ต 4000) — ต้องมี PostgreSQL ที่เชื่อมต่อได้',
  roleServerDb: 'การเชื่อมต่อฐานข้อมูล PostgreSQL (DATABASE_URL) — เว้นว่างหากตั้งใน .env แล้ว',
  connectThisMachine: 'เชื่อมต่อเครื่องนี้',
  // Back-office navigation (sections + items)
  navOverview: 'ภาพรวม',
  navSales: 'การขาย',
  navInventory: 'สินค้าคงคลัง',
  navCustomers: 'ลูกค้าและคู่ค้า',
  navFinance: 'การเงินและรายงาน',
  navSystem: 'ตั้งค่าระบบ',
  navDashboard: 'แดชบอร์ด',
  navSalesList: 'รายการขาย',
  navQuotations: 'ใบเสนอราคา',
  navLayaways: 'ออมก่อนรับ / มัดจำ',
  navReturns: 'การคืนสินค้า',
  navPromotions: 'การตลาด',
  navGiftCards: 'บัตรของขวัญ',
  navProducts: 'สินค้า',
  navLabels: 'พิมพ์ป้ายราคา/บาร์โค้ด',
  navMovements: 'คลังสินค้า',
  navTransfers: 'โอนสินค้าระหว่างสาขา',
  navPurchaseOrders: 'ใบสั่งซื้อ',
  navReceive: 'จัดซื้อ / รับเข้า',
  navSerials: 'ซีเรียล / รับประกัน',
  navMembers: 'ลูกค้า / สมาชิก',
  navSuppliers: 'ผู้จำหน่าย',
  navShifts: 'การเงิน / กะ',
  navExpenses: 'ค่าใช้จ่าย',
  navPayables: 'เจ้าหนี้การค้า',
  navTaxInvoices: 'รายงานภาษีขาย',
  navReports: 'รายงาน',
  navCustomReports: 'รายงานแบบกำหนดเอง',
  navSettings: 'ตั้งค่า',
  navBranches: 'สาขา',
  navUsers: 'ผู้ใช้งานระบบ',
  navAudit: 'บันทึกการใช้งาน',
  navBackup: 'สำรอง / กู้คืนข้อมูล',
  // Shared list-page chrome (ListToolbar / DataTable)
  tbSearch: 'ค้นหา…',
  tbFilter: 'ตัวกรอง',
  tbAdvFilter: 'ตัวกรองขั้นสูง',
  tbClearFilter: 'ล้างตัวกรอง',
  tbApplyFilter: 'ใช้ตัวกรอง',
  tbExport: 'ส่งออก',
  tbImagesZip: 'รูปภาพ + CSV (.zip)',
  tbNoData: 'ไม่มีข้อมูล',
  discountOverCap: (pct: number) => `ส่วนลดเกินเพดานของแคชเชียร์ (สูงสุด ${pct}% ของยอดสินค้า)`,
};

const enDict: typeof thDict = {
  frontRegister: 'Front register (Cashier)',
  retail: 'Retail',
  wholesale: 'Wholesale',
  backStore: 'Back office',
  signOut: 'Sign out',
  searchPlaceholder: 'Scan barcode or search product / SKU…',
  camera: 'Camera',
  favorites: 'Best sellers',
  allProducts: 'All products',
  searchResults: 'Search results',
  noProducts: 'No products found',
  emptyCartTitle: 'Scan or pick a product to start a sale',
  emptyCartHint: 'The barcode scanner works automatically — just scan',
  order: 'Order',
  items: 'pcs',
  item: 'Product',
  qty: 'Qty',
  price: 'Price',
  total: 'Total',
  subtotal: 'Subtotal',
  taxIncl: 'Tax (incl.)',
  taxExcl: 'Tax (excl.)',
  totalDue: 'Total due',
  charge: 'Take payment',
  clearOrder: 'Clear order',
  stock: 'Stock',
  outOfStock: 'Out of stock',
  wholesaleBadge: 'Wholesale',
  needMoreForWholesale: (n: number) => `Buy ≥${n} for wholesale`,
  added: (n: string) => `Added ${n}`,
  notFound: (c: string) => `No product with code "${c}"`,
  takePayment: 'Take payment',
  cash: 'Cash',
  transfer: 'Transfer (PromptPay)',
  cashReceived: 'Cash received',
  exact: 'Exact',
  reset: 'Reset',
  change: 'Change',
  cancel: 'Cancel',
  confirmCash: 'Confirm cash',
  markPaid: 'Mark paid',
  processing: 'Processing…',
  generatingQR: 'Generating QR…',
  thaiQR: 'Pay by QR',
  amount: 'Amount',
  scanToPay: 'Scan with any banking app to pay',
  noPromptPay: 'PromptPay not set — go to Back office → Settings',
  paymentComplete: 'Payment complete',
  newOrder: 'New order',
  openShift: 'Open shift',
  closeShift: 'Close shift',
  openingFloat: 'Opening float',
  openShiftTitle: 'Open a sales shift',
  openShiftHint: 'Enter the starting cash in the drawer to begin',
  startSelling: 'Start selling',
  shift: 'Shift',
  closeShiftTitle: 'Close shift & summary',
  countedCash: 'Counted cash',
  expectedCash: 'Expected cash',
  difference: 'Difference',
  cashSales: 'Cash sales',
  transferSales: 'Transfer sales',
  orders: 'Orders',
  confirmClose: 'Confirm close',
  shiftClosed: 'Shift closed',
  splitPayment: 'Split payment',
  addTender: 'Add tender',
  cashInOut: 'Cash in/out',
  cashDrawerTitle: 'Drawer cash in/out',
  payIn: 'Pay in',
  payOut: 'Pay out',
  cashReason: 'Reason / note',
  cashReasonHint: 'e.g. add change, pay utilities, bank deposit',
  recordCash: 'Record',
  cashRecorded: 'Cash movement recorded',
  noCashMoves: 'No cash movements yet',
  xReport: 'Sales report (X)',
  zReport: 'Print close report (Z)',
  printReport: 'Print report',
  member: 'Member',
  selectMember: 'Select member',
  searchMember: 'Search by name or phone…',
  noMember: 'Walk-in customer',
  addMember: 'Add new member',
  memberName: 'Member name',
  phone: 'Phone',
  save: 'Save',
  remove: 'Remove',
  memberPrice: 'Member price',
  max: 'Max',
  pointsUnit: 'pts',
  pointsBalance: 'Points balance',
  usePoints: 'Use points',
  pointsRedeemed: 'Points discount',
  pointsEarned: 'Points earned',
  customerDisplay: 'Customer display',
  welcome: 'Welcome',
  pleaseScan: 'Scan the QR to pay',
  waitingPayment: 'Waiting for payment',
  thankYou: 'Thank you',
  posTitle: 'Point of Sale (POS)',
  online: 'Online',
  searchFull: 'Search product / scan barcode / name / code',
  aCustomer: 'Customer',
  aPromotion: 'Promotion',
  aDiscount: 'Price/Discount',
  aHold: 'Hold bill',
  aLastBill: 'Last bill',
  aMore: 'More',
  kSalesToday: "Today's sales",
  kSalesMonth: "This month's sales",
  kProfitToday: "Today's gross profit",
  kCustomersToday: 'Customers today',
  kBills: 'bills',
  kFromLastMonth: 'from last month',
  kAvgPurchase: 'Avg. purchase',
  cAll: 'All',
  manageCategories: 'Manage categories',
  fBestSeller: 'Best seller',
  fAll: 'All',
  fBrand: 'Brand',
  fStockStatus: 'Stock status',
  bBestSeller: 'Best seller',
  bPromo: 'Promo',
  bLow: 'Low',
  bOut: 'Out',
  show: 'Show',
  perPage: '/ page',
  currentBill: 'Current bill',
  customerInfo: 'Customer info',
  changeCustomer: 'Change customer',
  generalCustomer: 'Walk-in customer',
  regularCustomer: 'Regular customer',
  cProduct: 'Product',
  cQty: 'Qty',
  cPrice: 'Price',
  cSum: 'Total',
  discountCoupon: 'Discount / coupon',
  add: 'Add',
  subtotalItems: 'Items subtotal',
  billDiscount: 'Bill discount',
  vatLabel: 'VAT',
  netTotal: 'Net total',
  received: 'Received',
  pmCash: 'Cash',
  pmTransfer: 'Transfer',
  pmCard: 'Card',
  pmQR: 'QR Code',
  pmCredit: 'Credit',
  pay: 'Pay',
  emptyBill: 'No items in the bill yet',
  scanToStart: 'Scan or pick a product to start',
  comingSoon: 'This feature is coming soon',
  held: 'Bill held',
  noHeld: 'No held bills',
  confirmPayment: 'Confirm payment',
  branch: 'Branch',
  switchBranch: 'Switch branch',
  offlineSaleQueued: 'Sale saved offline — will sync automatically when back online',
  pendingSync: 'Pending sync',
  syncNow: 'Sync now',
  syncing: 'Syncing…',
  offline: 'Offline',
  foreignCash: 'Take foreign-currency cash',
  foreignTender: 'Foreign tender',
  pendingSyncTitle: 'Offline sales pending sync',
  pendingSyncEmpty: 'Nothing pending sync',
  syncFailed: 'Sync failed',
  discard: 'Discard',
  discardConfirm: 'Discard this offline sale? It will not be recorded.',
  serverConnect: 'Server connection',
  serverUrl: 'POS server address (URL)',
  serverHint: 'e.g. http://192.168.1.50:4000 — leave blank to use the server that served this app',
  serverSaved: 'Connection saved. Reloading…',
  serverReachable: 'Connected to server ✓',
  serverUnreachable: 'Could not connect to server',
  testConnection: 'Test connection',
  back: 'Back',
  desktopSetupTitle: 'Initial setup',
  desktopSetupSub: "Choose this machine's role to start using the POS",
  roleServer: 'Server (main machine)',
  roleServerHint: 'This machine hosts the data / serves the POS to the other terminals in the shop',
  roleClient: 'Client (register)',
  roleClientHint: "A register that connects to the shop's server",
  roleServerNote: 'This machine will run the POS server itself (port 4000) — a reachable PostgreSQL is required',
  roleServerDb: 'PostgreSQL connection (DATABASE_URL) — leave blank if set in .env',
  connectThisMachine: 'Connect this machine',
  navOverview: 'Overview',
  navSales: 'Sales',
  navInventory: 'Inventory',
  navCustomers: 'Customers & partners',
  navFinance: 'Finance & reports',
  navSystem: 'System',
  navDashboard: 'Dashboard',
  navSalesList: 'Sales',
  navQuotations: 'Quotations',
  navLayaways: 'Layaway / deposits',
  navReturns: 'Returns',
  navPromotions: 'Marketing',
  navGiftCards: 'Gift cards',
  navProducts: 'Products',
  navLabels: 'Price/barcode labels',
  navMovements: 'Stock movements',
  navTransfers: 'Branch transfers',
  navPurchaseOrders: 'Purchase orders',
  navReceive: 'Purchasing / receiving',
  navSerials: 'Serials / warranty',
  navMembers: 'Members',
  navSuppliers: 'Suppliers',
  navShifts: 'Cash / shifts',
  navExpenses: 'Expenses',
  navPayables: 'Payables',
  navTaxInvoices: 'Tax invoices',
  navReports: 'Reports',
  navCustomReports: 'Custom reports',
  navSettings: 'Settings',
  navBranches: 'Branches',
  navUsers: 'System users',
  navAudit: 'Audit log',
  navBackup: 'Backup / restore',
  tbSearch: 'Search…',
  tbFilter: 'Filter',
  tbAdvFilter: 'Advanced filter',
  tbClearFilter: 'Clear filter',
  tbApplyFilter: 'Apply filter',
  tbExport: 'Export',
  tbImagesZip: 'Images + CSV (.zip)',
  tbNoData: 'No data',
  discountOverCap: (pct: number) => `Discount exceeds the cashier cap (max ${pct}% of items)`,
};

export type Lang = 'th' | 'en';
const LANG_KEY = 'pos_lang';

export function getLang(): Lang {
  return typeof localStorage !== 'undefined' && localStorage.getItem(LANG_KEY) === 'en' ? 'en' : 'th';
}

/** Switch UI language and reload so the active dictionary is re-applied everywhere. */
export function setLang(lang: Lang) {
  if (typeof localStorage !== 'undefined') localStorage.setItem(LANG_KEY, lang);
  if (typeof location !== 'undefined') location.reload();
}

// The active dictionary, chosen once at load. All `th.x` call sites use this unchanged.
export const th = getLang() === 'en' ? enDict : thDict;
