-- AlterTable
ALTER TABLE "Setting" ADD COLUMN     "smtpFrom" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "smtpHost" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "smtpPass" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "smtpPort" INTEGER NOT NULL DEFAULT 587,
ADD COLUMN     "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpUser" TEXT NOT NULL DEFAULT '';
